///////////////////////////////////////////////////////////////////////////////
// ListenerModule.cpp
#include "TcPch.h"
#pragma hdrstop

#include "ListenerModule.h"
#include "PublisherListenerVersion.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CListenerModule
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CListenerModule
BEGIN_INTERFACE_MAP(CListenerModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
	INTERFACE_ENTRY(IID_ITcAlarmListener, ITcAlarmListener)
	INTERFACE_ENTRY(IID_ITcMessageListener, ITcMessageListener)
///</AutoGeneratedContent>
END_INTERFACE_MAP()


IMPLEMENT_IPERSIST_LIB(CListenerModule, VID_PublisherListener, CID_PublisherListenerCListenerModule)
IMPLEMENT_ITCOMOBJECT(CListenerModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CListenerModule)
IMPLEMENT_ITCADI(CListenerModule)
IMPLEMENT_ITCWATCHSOURCE(CListenerModule)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CListenerModule 
BEGIN_SETOBJPARA_MAP(CListenerModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_ListenerModuleParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CListenerModule 
BEGIN_GETOBJPARA_MAP(CListenerModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_ListenerModuleParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CListenerModule
BEGIN_OBJPARAWATCH_MAP(CListenerModule)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CListenerModule
BEGIN_OBJDATAAREA_MAP(CListenerModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_ListenerModuleInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_ListenerModuleOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CListenerModule::CListenerModule()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_counter(0)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_Parameter, 0, sizeof(m_Parameter));
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CListenerModule::~CListenerModule() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CListenerModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CListenerModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// TODO: Add initialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CListenerModule::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization
	m_spEventLogger.SetOID(OID_TCEVENTLOGGER);
	hr = FAILED(hr) ? hr : m_spSrv->TcQuerySmartObjectInterface(m_spEventLogger);
	hr = FAILED(hr) ? hr : m_spEventLogger->AddMessageListener(this, &m_spMessageFilterConfig);
	hr = FAILED(hr) ? hr : m_spEventLogger->AddAlarmListener(this, &m_spAlarmFilterConfig);
	if (m_spMessageFilterConfig)
	{
		m_spMessageFilterConfig->AddEventClass(TcEvents::MyCppEventClass::EventClass, TcEventSeverity::Verbose);
	}
	if (m_spAlarmFilterConfig)
	{
		m_spAlarmFilterConfig->AddEventClass(TcEvents::MyCppEventClass::EventClass, TcEventSeverity::Verbose);
	}

	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
		m_spEventLogger = NULL;
		m_spMessageFilterConfig = NULL;
		m_spAlarmFilterConfig = NULL; 
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CListenerModule::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	// TODO: Add any additional deinitialization
	if (m_spEventLogger)
	{
		m_spEventLogger->RemoveMessageListener(this);
		m_spEventLogger->RemoveAlarmListener(this);

		m_spEventLogger = NULL;
		m_spMessageFilterConfig = NULL;
		m_spAlarmFilterConfig = NULL;
	}
	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CListenerModule::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// TODO: Add deinitialization code
	m_spEventLogger = NULL;
	m_spMessageFilterConfig = NULL;
	m_spAlarmFilterConfig = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CListenerModule::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// TODO: Replace the sample with your cyclic code
	if (m_spEventLogger)
	{
		m_spEventLogger->NotifyMessageListener(this);
		m_spEventLogger->NotifyAlarmListener(this);
	}
	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CListenerModule::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CListenerModule::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}


///<AutoGeneratedContent id="ImplementationOf_ITcAlarmListener">
HRESULT CListenerModule::OnAlarmRaised(ITcEvent* ipEvent)
{
	HRESULT hr = S_OK;
	m_Outputs.nReceivedAlarmRaise++;
	return hr;
}

HRESULT CListenerModule::OnAlarmCleared(ITcEvent* ipEvent)
{
	HRESULT hr = S_OK;
	m_Outputs.nReceivedAlarmClear++;
	return hr;
}

HRESULT CListenerModule::OnAlarmConfirmed(ITcEvent* ipEvent)
{
	HRESULT hr = S_OK;
	m_Outputs.nReceivedAlarmConfirm++;
	return hr;
}

HRESULT CListenerModule::OnAlarmDisposed(ITcEvent* ipEvent)
{
	HRESULT hr = S_OK;
	m_Outputs.nReceivedAlarmDispose++;
	return hr;
}
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ImplementationOf_ITcMessageListener">
HRESULT CListenerModule::OnMessageSent(ITcEvent* ipEvent)
{
	HRESULT hr = S_OK;
	m_Outputs.nReceivedMessages++;
	return hr;
}
///</AutoGeneratedContent>
