///////////////////////////////////////////////////////////////////////////////
// StartStopMsgsInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "StartStopMsgsServices.h"
#include "TcEventLoggerTemplates.h"
#include "TcRouterServices.h"
///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
