///////////////////////////////////////////////////////////////////////////////
// StartStopMsgsClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "StartStopMsgsClassFactory.h"
#include "StartStopMsgsServices.h"
#include "StartStopMsgsVersion.h"
#include "StartStopMsgsModule.h"

BEGIN_CLASS_MAP(CStartStopMsgsClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_StartStopMsgs, CID_StartStopMsgsCStartStopMsgsModule, SRVNAME_STARTSTOPMSGS "!CStartStopMsgsModule", CStartStopMsgsModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CStartStopMsgsClassFactory::CStartStopMsgsClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_STARTSTOPMSGS)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(StartStopMsgs));
#endif //defined(TCDBG_UNIT_VERSION)
}

