///////////////////////////////////////////////////////////////////////////////
// StartStopMsgsModule.cpp
#include "TcPch.h"
#pragma hdrstop

#include "StartStopMsgsModule.h"
#include "StartStopMsgsVersion.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CStartStopMsgsModule
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CStartStopMsgsModule
BEGIN_INTERFACE_MAP(CStartStopMsgsModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()


IMPLEMENT_IPERSIST_LIB(CStartStopMsgsModule, VID_StartStopMsgs, CID_StartStopMsgsCStartStopMsgsModule)
IMPLEMENT_ITCOMOBJECT(CStartStopMsgsModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CStartStopMsgsModule)
IMPLEMENT_ITCADI(CStartStopMsgsModule)
IMPLEMENT_ITCWATCHSOURCE(CStartStopMsgsModule)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CStartStopMsgsModule 
BEGIN_SETOBJPARA_MAP(CStartStopMsgsModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_StartStopMsgsModuleParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CStartStopMsgsModule 
BEGIN_GETOBJPARA_MAP(CStartStopMsgsModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_StartStopMsgsModuleParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CStartStopMsgsModule
BEGIN_OBJPARAWATCH_MAP(CStartStopMsgsModule)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CStartStopMsgsModule
BEGIN_OBJDATAAREA_MAP(CStartStopMsgsModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_StartStopMsgsModuleInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_StartStopMsgsModuleOutputs, m_Outputs)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CStartStopMsgsModule::CStartStopMsgsModule()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, m_counter(0)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_Parameter, 0, sizeof(m_Parameter));
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CStartStopMsgsModule::~CStartStopMsgsModule() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CStartStopMsgsModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CStartStopMsgsModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// TODO: Add initialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CStartStopMsgsModule::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization

	m_spEventLogger.SetOID(OID_TCEVENTLOGGER);
	hr = FAILED(hr) ? hr : m_spSrv->TcQuerySmartObjectInterface(m_spEventLogger);
	hr = FAILED(hr) ? hr : CreateMessage(TcEvents::TcComMessages::EventloggerInitialized, &m_spMsgsEventloggerInit);
	hr = FAILED(hr) ? hr : CreateMessage(TcEvents::TcComMessages::EventloggerDeinitialized, &m_spMsgsEventloggerDeinit);
	hr = FAILED(hr) ? hr : CreateMessage(TcEvents::TcComMessages::SetObjStateSODone, &m_spMsgsSODone);
	hr = FAILED(hr) ? hr : CreateMessage(TcEvents::TcComMessages::SetObjStateOSDone, &m_spMsgsOSDone);
	hr = FAILED(hr) ? hr : CreateMessage(TcEvents::TcComMessages::AddModuleToCallerDone, &m_spMsgsAddModuleDone);
	hr = FAILED(hr) ? hr : CreateMessage(TcEvents::TcComMessages::RemoveModuleFromCallerDone, &m_spMsgsRemoveModuleDone);
	hr = FAILED(hr) ? hr : m_spMsgsEventloggerInit->Send(0);
	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}

	hr = FAILED(hr) ? hr : m_spMsgsSODone->Send(0);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CStartStopMsgsModule::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	// TODO: Add any additional deinitialization

	// free eventlogger resources
	hr = FAILED(hr) ? hr : m_spMsgsEventloggerDeinit->Send(0);
	hr = FAILED(hr) ? hr : m_spMsgsOSDone->Send(0);

	m_spMsgsEventloggerInit = NULL;
	m_spMsgsEventloggerDeinit = NULL;
	m_spMsgsSODone = NULL;
	m_spMsgsOSDone = NULL;
	m_spMsgsAddModuleDone = NULL;
	m_spMsgsRemoveModuleDone = NULL;
	m_spEventLogger = NULL;

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CStartStopMsgsModule::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// TODO: Add deinitialization code
	

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CStartStopMsgsModule::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// TODO: Replace the sample with your cyclic code
	m_counter+=m_Inputs.Value;
	m_Outputs.Value=m_counter;

	return hr;
}
///</AutoGeneratedContent>

///////////////////////////////////////////////////////////////////////////////
HRESULT CStartStopMsgsModule::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_spMsgsAddModuleDone->Send(0);

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CStartStopMsgsModule::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;
	m_spMsgsRemoveModuleDone->Send(0);

	m_Trace.Log(tlVerbose, FLEAVEA);
}

