///////////////////////////////////////////////////////////////////////////////
// StartStopMsgsModule.h
#pragma once

#include "StartStopMsgsInterfaces.h"

class CStartStopMsgsModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public ITcCyclic
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CStartStopMsgsModule();
	virtual	~CStartStopMsgsModule();


///<AutoGeneratedContent id="InterfaceMembers">
	// ITcCyclic
	virtual HRESULT TCOMAPI CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context);

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

	HRESULT AddModuleToCaller();
	VOID RemoveModuleFromCaller();

	// Tracing
	CTcTrace m_Trace;
	ITcEventLoggerPtr	m_spEventLogger;
	ITcMessagePtr		m_spMsgsEventloggerInit;
	ITcMessagePtr		m_spMsgsEventloggerDeinit;
	ITcMessagePtr		m_spMsgsPSDone;
	ITcMessagePtr		m_spMsgsSODone;
	ITcMessagePtr		m_spMsgsOSDone;
	ITcMessagePtr		m_spMsgsSPDone;
	ITcMessagePtr		m_spMsgsAddModuleDone;
	ITcMessagePtr		m_spMsgsRemoveModuleDone;

///<AutoGeneratedContent id="Members">
	TcTraceLevel m_TraceLevelMax;
	StartStopMsgsModuleParameter m_Parameter;
	StartStopMsgsModuleInputs m_Inputs;
	StartStopMsgsModuleOutputs m_Outputs;
	ITcCyclicCallerInfoPtr m_spCyclicCaller;
///</AutoGeneratedContent>


	HRESULT CreateMessage(TcEventEntry entry, ITcMessage** iipMessage)
	{
		return m_spEventLogger->CreateMessage(entry.uuidEventClass, entry.nEventId, entry.eSeverity, &TcSourceInfo("TcCOM Startup/Shutdown"), iipMessage);
	}

	// TODO: Custom variable
	UINT m_counter;
};
