///////////////////////////////////////////////////////////////////////////////
// StartStopMsgsServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_StartStopMsgs = 0x3F000000;
#define SRVNAME_STARTSTOPMSGS "StartStopMsgs"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_StartStopMsgsCStartStopMsgsModule = {0xa06cf2d1,0x3600,0x4c82,{0xa8,0x81,0x28,0xb6,0x71,0xfe,0x0a,0x69}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_StartStopMsgsModuleParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _StartStopMsgsModuleParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} StartStopMsgsModuleParameter, *PStartStopMsgsModuleParameter;

typedef struct _StartStopMsgsModuleInputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
} StartStopMsgsModuleInputs, *PStartStopMsgsModuleInputs;

typedef struct _StartStopMsgsModuleOutputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
} StartStopMsgsModuleOutputs, *PStartStopMsgsModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_StartStopMsgsModuleInputs 0
#define ADI_StartStopMsgsModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
#if !defined(_TC_TYPE_B01D11FA_E667_4416_9CCA_9C2FDCBA0D44_INCLUDED_)
#define _TC_TYPE_B01D11FA_E667_4416_9CCA_9C2FDCBA0D44_INCLUDED_
namespace TcEvents
{
	namespace TcComMessages
	{
		CONSTEXPR const GUID EventClass = {0xb01d11fa,0xe667,0x4416,{0x9c,0xca,0x9c,0x2f,0xdc,0xba,0x0d,0x44}};

		struct EventIds
		{
			enum
			{
					EventloggerInitialized =  1, //Eventlogger initialized
					EventloggerDeinitialized =  2, //Eventlogger deinitialized
					SetObjStatePSDone =  3, //SetObjStatePS Done
					SetObjStateSODone =  4, //SetObjStateSO Done
					SetObjStateOSDone =  5, //SetObjStateOS Done
					SetObjStateSPDone =  6, //SetObjStateSP Done
					AddModuleToCallerDone =  7, //AddModuleToCaller Done
					RemoveModuleFromCallerDone =  8, //RemoveModuleFromCaller Done
			};
		};

		CONSTEXPR const TcEventEntry EventloggerInitialized = { EventClass, EventIds::EventloggerInitialized, TcEventSeverity::Verbose };
		CONSTEXPR const TcEventEntry EventloggerDeinitialized = { EventClass, EventIds::EventloggerDeinitialized, TcEventSeverity::Verbose };
		CONSTEXPR const TcEventEntry SetObjStatePSDone = { EventClass, EventIds::SetObjStatePSDone, TcEventSeverity::Verbose };
		CONSTEXPR const TcEventEntry SetObjStateSODone = { EventClass, EventIds::SetObjStateSODone, TcEventSeverity::Verbose };
		CONSTEXPR const TcEventEntry SetObjStateOSDone = { EventClass, EventIds::SetObjStateOSDone, TcEventSeverity::Verbose };
		CONSTEXPR const TcEventEntry SetObjStateSPDone = { EventClass, EventIds::SetObjStateSPDone, TcEventSeverity::Verbose };
		CONSTEXPR const TcEventEntry AddModuleToCallerDone = { EventClass, EventIds::AddModuleToCallerDone, TcEventSeverity::Verbose };
		CONSTEXPR const TcEventEntry RemoveModuleFromCallerDone = { EventClass, EventIds::RemoveModuleFromCallerDone, TcEventSeverity::Verbose };
	};
};
#endif // !defined(_TC_TYPE_B01D11FA_E667_4416_9CCA_9C2FDCBA0D44_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>
