<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.10">
  <POU Name="MAIN" Id="{e5156229-dc7e-47cb-bfdc-7d4aa00249b1}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbListenerTest : FB_ListenerTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbListenerTest();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="28" Count="0" />
      <LineId Id="27" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>